sudo: false
language: node_js
before_install:
  - "npm install npm -g"
node_js:
  - "stable"
  - "4"
  - "5"
  - "6"
  - "0.10"
  - "0.12"
node_js:
    - "v4"
install:
    - npm install
script:
    - npm run test